elastic/opentelemetry-collector-components

.github/workflows/checks.yml
Makefile
distributions/elastic-components/config.yaml
distributions/elastic-components/manifest.yaml

- Update manifest file to reference local package
- Validate make target: compile + configuration validation

Add the elasticinframetricsprocessor to the components distribution manifest

---

processor/elasticinframetricsprocessor/config.go
processor/elasticinframetricsprocessor/config_test.go
processor/elasticinframetricsprocessor/factory.go
processor/elasticinframetricsprocessor/go.mod
processor/elasticinframetricsprocessor/go.sum
processor/elasticinframetricsprocessor/processor.go
processor/elasticinframetricsprocessor/processor_test.go
processor/elasticinframetricsprocessor/testdata/config.yaml

Description:
Add kubernetes metrics remapping and corresponding `add_k8s_metrics` configuration
Testing:

Add add_kubernetes_metrics configuration

---

connector/spanmetricsconnectorv2/connector.go
connector/spanmetricsconnectorv2/histogram.go

Fixes the incorrect allocation logic

[connector/spanmetricsv2] Fix allocation logic

---

processor/elastictraceprocessor/testdata/elastic_span_db/output.yaml
processor/elastictraceprocessor/testdata/elastic_span_http/output.yaml
processor/elastictraceprocessor/testdata/elastic_span_messaging/output.yaml
processor/elastictraceprocessor/testdata/elastic_txn_db/output.yaml
processor/elastictraceprocessor/testdata/elastic_txn_http/output.yaml
processor/elastictraceprocessor/testdata/elastic_txn_messaging/output.yaml

#106 PR got merged without all tests passing (I think there is a transient state where the CLA check is enough to call the build success). This PR fixes the test failure due to that.

[processor/elastictrace] Fix testcases after upgrade of otel lib

---

connector/signaltometricsconnector/internal/aggregator/aggregator.go

This is an edge-case which is not that important anymore but for consistency fixing this.

[connector/signaltometrics] Cleanup sums cache after finalize

---

.github/workflows/checks.yml

github-actions: set contents: read permission at the top level

---

.github/dependabot.yml

Add ratelimitprocessor to dependabot.yml

---

processor/lsmintervalprocessor/processor.go

Removes the next processor call from the critical section.

[processor/lsminterval]Optimize critical section

---

loadgen/cmd/otelsoak/README.md
loadgen/cmd/otelsoak/config.example.yaml

Ensure that readme example usages work

[otelsoak] Fix example usage in readme

---

processor/lsmintervalprocessor/processor_test.go

Related to https://github.com/elastic/opentelemetry-collector-components/issues/245,  https://github.com/elastic/opentelemetry-collector-components/issues/211, and #346

[processor/lsminterval]Add parallel benchmark for aggregation

---

.github/workflows/checks.yml
connector/signaltometricsconnector/go.mod
extension/beatsauthextension/go.mod
internal/testutil/go.mod
internal/tools/go.mod
loadgen/cmd/otelbench/go.mod
processor/elasticinframetricsprocessor/go.mod
processor/elastictraceprocessor/go.mod
processor/lsmintervalprocessor/go.mod
processor/ratelimitprocessor/go.mod
receiver/elasticapmreceiver/go.mod
receiver/loadgenreceiver/go.mod

Require Go 1.23, test with Go 1.24.

Update to Go 1.23

---

processor/lsmintervalprocessor/processor.go

The PR limits the iteration on harvest to one interval size (which should be where data lies) as well as optimizes the delete range to only run if the range has data to prevent unnecessary tombstones.

Limit harvest interval and optimize range delete

---

.github/workflows/bump_otelbench.yaml
.github/workflows/release_otelbench.yaml

I wrote the wrong path for the scripts and it failed. See https://github.com/elastic/opentelemetry-collector-components/actions/runs/13699555298/job/38309688903.

[workflow/otelbench] Fix path to scripts

---

.github/workflows/bump_otelbench.yaml
.github/workflows/scripts/create_pr.sh

Sorry for the multiple PRs. Hopefully this is the last change required to make this work.
See the error: https://github.com/elastic/opentelemetry-collector-components/actions/runs/13700951273/job/38314348328.

[workflow/otelbench] Fix chloggen tool path

---

.github/workflows/bump_otelbench.yaml

We need the token before we checkout.

[workflow/otelbench] Get token before checkout

---

receiver/elasticapmreceiver/testdata/language_name_mapping_expected.yaml

A leftover from https://github.com/elastic/opentelemetry-collector-components/pull/388

[receiver/elasticapm] Fix timestamps in test file

---

receiver/loadgenreceiver/logs.go
receiver/loadgenreceiver/metrics.go
receiver/loadgenreceiver/traces.go

Fix context canceled by waiting for all in flight Consume* to finish at their own pace.
Before:
```
2025-03-19T13:24:16.715+0100    info    otelcol@v0.120.0/collector.go:339       Received signal from OS {"signal": "terminated"}
2025-03-19T13:24:16.715+0100    info    service@v0.120.0/service.go:323 Starting shutdown...
2025-03-19T13:24:16.715+0100    info    internal/retry_sender.go:126    Exporting failed. Will retry the request after interval.        {"otelcol.component.id": "otlp", "otelcol.component.kind": "Exporter", "otelcol.signal": "traces", "error": "rpc error: code = Canceled desc = context canceled", "interval": "4.320519191s"}
2025-03-19T13:24:16.715+0100    info    internal/retry_sender.go:126    Exporting failed. Will retry the request after interval. …
```

[receiver/loadgen] Allow graceful shutdown and avoid context canceled

---

.github/CODEOWNERS

Needs an update to Terrazzo too, to give write access to the team.

Add @elastic/ingest-tech-lead as code owners

---

extension/apmconfigextension/go.mod
extension/apmconfigextension/go.sum

idempotency issue in tests https://github.com/open-telemetry/opamp-go/pull/348

chore: pin opamp-go that fixes restart

---

extension/apmconfigextension/extension.go
extension/apmconfigextension/logger.go

Fixes https://github.com/elastic/opentelemetry-collector-components/issues/580

chore: add opAMPLogger wrapper for zap logging

---

processor/elasticapmprocessor/processor.go

- Add datastream routing and ECS context handling to metrics and logs
This is a follow up of https://github.com/elastic/opentelemetry-collector-components/pull/633 and https://github.com/elastic/opentelemetry-collector-components/pull/634,

[processor/elasticapmprocessor] Add datastream routing and ECS context handling to metrics and logs

---

connector/elasticapmconnector/connector_test.go
processor/lsmintervalprocessor/processor.go
processor/lsmintervalprocessor/processor_test.go

Closes https://github.com/elastic/opentelemetry-collector-components/issues/661

[processor/lsminterval]Send to next component only if datapoints are present

---

receiver/elasticapmintakereceiver/internal/attributes.go
receiver/elasticapmintakereceiver/internal/mappers/intakeV2ToElasticSpecificFields.go
receiver/elasticapmintakereceiver/internal/mappers/intakeV2ToSemConv.go
receiver/elasticapmintakereceiver/testdata/errors_expected.yaml
receiver/elasticapmintakereceiver/testdata/invalid_ids_expected.yaml
receiver/elasticapmintakereceiver/testdata/language_name_mapping_expected.yaml
receiver/elasticapmintakereceiver/testdata/metricsets_expected.yaml
receiver/elasticapmintakereceiver/testdata/spans_expected.yaml
receiver/elasticapmintakereceiver/testdata/transactions_expected.yaml
receiver/elasticapmintakereceiver/testdata/transactions_spans_expected.yaml
receiver/elasticapmintakereceiver/testdata/unknown-span-type_expected.yaml

Add mapping for cloud, container, k8s and other relevant fields
- related to https://github.com/elastic/opentelemetry-dev/issues/742

[receiver/elasticapmintake] Add mapping for cloud, container, k8s and other relevant fields

---

loadgen/cmd/otelbench/README.md

- Fix readme content
- Add example usage with docker image and custom config file

[loadgen/otelbench] docs: Add docker image usage with custom config
