.github/workflows/checks.yml, Makefile, Makefile.Common, internal/tools/empty.go, internal/tools/empty_test.go, internal/tools/go.mod, internal/tools/go.sum, internal/tools/tools.go
This PR adds a CI similar to the [OpenTelemetry Collector one](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/workflows/build-and-test.yml). It should help by automating the test process and ease the transition to upstream.
- Add `porto` and `govulncheck` tools
- CI pipeline with the following checks:
- Linter
- govulncheck
- porto, go tidy and go generate
- unit tests
=> Add pipeline checks

.github/dependabot.yml
Enables dependabot for dependencies PRs updates.
- Daily execution
- Ignores major changes: breaking changes might require manual changes and extra review.
=> ci: add dependabot for gomod and gha packages

.github/dependabot.yml
Specify which directories contain Go modules. For the moment, we need to replicate each dependabot entry configuration as wildcard patterns are not supported: https://github.com/dependabot/dependabot-core/issues/2178
Fixes: https://github.com/elastic/opentelemetry-collector-components/issues/9
=> ci: add Go directories to dependabot configuration 

.github/dependabot.yml
Should make it a bit easier to review and merge the OTel version bump PRs.
=> Add dependabot grouping for otel-collector-contrib repo

connector/spanmetricsconnectorv2/config.go, connector/spanmetricsconnectorv2/config_test.go, connector/spanmetricsconnectorv2/connector.go, connector/spanmetricsconnectorv2/connector_test.go, connector/spanmetricsconnectorv2/factory.go, connector/spanmetricsconnectorv2/histogram.go, connector/spanmetricsconnectorv2/metadata.yaml, connector/spanmetricsconnectorv2/model.go, connector/spanmetricsconnectorv2/testdata/with_attributes/config.yaml, connector/spanmetricsconnectorv2/testdata/with_custom_histogram_buckets/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_desc_different_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_desc_different_attrs/input.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_desc_different_attrs/output.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_different_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_different_attrs/input.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_different_attrs/output.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_identical_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_missing_attribute/config.yaml, connector/spanmetricsconnectorv2/testdata/with_missing_attribute_default_value/config.yaml
Allows creating span metrics with same metric name but different resource attributes.
=> [connector/spanmetricsv2] Use slice for spans config

connector/spanmetricsconnectorv2/config.go, connector/spanmetricsconnectorv2/config_test.go
The previous code was trying to normalize the buckets incorrectly, I have removed the normalization entirely as it was confusing for the end users that the buckets can change based on the unit configured.
=> [connector/spanmetrics] Use fixed default buckets for histograms

connector/spanmetricsconnectorv2/config/config.go, connector/spanmetricsconnectorv2/config/config_test.go, connector/spanmetricsconnectorv2/connector.go, connector/spanmetricsconnectorv2/connector_test.go, connector/spanmetricsconnectorv2/factory.go, connector/spanmetricsconnectorv2/internal/aggregator/aggregator.go, connector/spanmetricsconnectorv2/internal/aggregator/aggregator_explicit_test.go, connector/spanmetricsconnectorv2/internal/aggregator/explicithistogram.go, connector/spanmetricsconnectorv2/internal/aggregator/summary.go, connector/spanmetricsconnectorv2/internal/model/model.go, connector/spanmetricsconnectorv2/testdata/with_attributes/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_desc_different_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_different_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_identical_attrs/config.yaml, connector/spanmetricsconnectorv2/testdata/with_missing_attribute/config.yaml, connector/spanmetricsconnectorv2/testdata/with_missing_attribute_default_value/config.yaml, connector/spanmetricsconnectorv2/testdata/with_summary/config.yaml, connector/spanmetricsconnectorv2/testdata/with_summary/input.yaml, connector/spanmetricsconnectorv2/testdata/with_summary/output.yaml
Refactors the code a bit to allow for a single interface for updating all metrics and adds support for summary metric. Currently summary metric doesn't support quantiles.
Related to: https://github.com/elastic/opentelemetry-dev/issues/219
=> [connector/spanmetricsv2] Add support for summary metric

.github/workflows/checks.yml
<strike>I am a bit confused how this has been passing so far.</strike> As per my understanding, the codegen check should have been failing as the `make generate` cannot work from root but it has been passing so far: https://github.com/elastic/opentelemetry-collector-components/actions/runs/10321562649/job/28574769867?pr=85#step:10:1
The reason why this has been passing so far is because go1.21.10 version does not fail `go generate ./...` even though the root is not a go module:
```shell
lahsivjar@Vishals-MacBook-Pro: ~/Projects/elastic/opentelemetry-collector-components test-why
$ go version
go version go1.21.10 darwin/arm64
lahsivjar@Vishals-MacBook-Pro: ~/Projects/elastic/opentelemetry-collector-components test-why
$ go generate ./...
lahsivjar@Vishals-MacBook-Pro: …
```
=> Fix generate check

.github/workflows/checks.yml, connector/spanmetricsconnectorv2/go.mod, distributions/elastic-components/manifest.yaml, processor/elasticinframetricsprocessor/go.mod, processor/elastictraceprocessor/go.mod, processor/lsmintervalprocessor/go.mod
OTel has bumped up the minimum go version to 1.22. The PR bumps up the golang version for all components to 1.22.0 and checks from 1.21.10 to 1.22.7.
This should also fix vulnerability reports like https://pkg.go.dev/vuln/GO-2024-2687 which are reported in version up PRs like https://github.com/elastic/opentelemetry-collector-components/pull/116 -- it happens because with `GOTOOLCHAIN=auto` it downloads the toolchain based on to go version in go module IF the latest local version is less than the go version.
I am doing go version update of modules here instead of dependabot because dependabot seems to like introducing the `gotoolchain` directive everywhere.
=> Bump golang version to 1.22

connector/spanmetricsconnectorv2/config/config.go, connector/spanmetricsconnectorv2/config/config_test.go, connector/spanmetricsconnectorv2/connector_test.go, connector/spanmetricsconnectorv2/factory.go, connector/spanmetricsconnectorv2/internal/aggregator/aggregator.go, connector/spanmetricsconnectorv2/internal/aggregator/counters.go, connector/spanmetricsconnectorv2/internal/model/model.go, connector/spanmetricsconnectorv2/testdata/with_counters/config.yaml, connector/spanmetricsconnectorv2/testdata/with_counters/input.yaml, connector/spanmetricsconnectorv2/testdata/with_counters/output.yaml
Allows aggregating the span as 2 separate counters with customizable suffixes. The counters represent sum of span duration and count of spans respectively.
Related to: https://github.com/elastic/opentelemetry-dev/issues/372
=> [connector/spanmetricsv2] Aggregate spans as 2 counters

connector/spanmetricsconnectorv2/generated_component_test.go, connector/spanmetricsconnectorv2/go.mod, connector/spanmetricsconnectorv2/internal/metadata/generated_status.go, distributions/elastic-components/manifest.yaml
Updates the files produced by mdatagen. For some reason, `make generate` is using an older version of `mdatagen` and not generating the correct files (I think it has something to do with `GOBIN`) so these files are generated by using the latest version of `mdatagen` directly. Not sure what version CI is picking but we should see that in the PR build results.
=> Update metadata produced by mdatagen

connector/spanmetricsconnectorv2/internal/aggregator/aggregator.go, connector/spanmetricsconnectorv2/internal/aggregator/aggregator_explicit_test.go, connector/spanmetricsconnectorv2/internal/metadata/generated_status.go, connector/spanmetricsconnectorv2/metadata.yaml, connector/spanmetricsconnectorv2/testdata/with_attributes/output.yaml, connector/spanmetricsconnectorv2/testdata/with_counters/output.yaml, connector/spanmetricsconnectorv2/testdata/with_custom_histogram_configs/output.yaml, connector/spanmetricsconnectorv2/testdata/with_default/output.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_desc_different_attrs/output.yaml, connector/spanmetricsconnectorv2/testdata/with_identical_metric_name_different_attrs/output.yaml, connector/spanmetricsconnectorv2/testdata/with_include_resource_attributes/output.yaml, connector/spanmetricsconnectorv2/testdata/with_missing_attribute_default_value/output.yaml, connector/spanmetricsconnectorv2/testdata/with_summary/output.yaml, processor/elastictraceprocessor/generated_component_test.go, processor/elastictraceprocessor/internal/metadata/generated_status.go, processor/elastictraceprocessor/metadata.yaml, processor/lsmintervalprocessor/generated_component_test.go, processor/lsmintervalprocessor/internal/metadata/generated_status.go, processor/lsmintervalprocessor/metadata.yaml
Updates scope names of internal components to use fully qualified names for consistency
=> Use fully qualified names as scope name

processor/lsmintervalprocessor/internal/merger/model.go, processor/lsmintervalprocessor/testdata/histogram_cumulative/input.yaml, processor/lsmintervalprocessor/testdata/histogram_cumulative/output.yaml, processor/lsmintervalprocessor/testdata/histogram_delta/input.yaml, processor/lsmintervalprocessor/testdata/histogram_delta/output.yaml
In https://github.com/elastic/opentelemetry-collector-components/pull/151 we vendored data package from upstream. In this PR, I have updated all our merges to use the vendored code since we already have it.
=> [processor/lsminterval]Use vendored data package for all merges

Makefile
Rewrite filtering of files when discovering modules to use `find` options and exclude `_build` directory.
Including `_build` makes some targets to fail if the directory exists:
```
$ make gotest
make[1]: Entering directory '/home/jaime/gocode/src/github.com/elastic/opentelemetry-collector-components'
Running target 'test' in module '_build'
make -C _build test
make[2]: Entering directory '/home/jaime/gocode/src/github.com/elastic/opentelemetry-collector-components/_build'
make[2]: *** No rule to make target 'test'.  Stop.
make[2]: Leaving directory '/home/jaime/gocode/src/github.com/elastic/opentelemetry-collector-components/_build'
make[1]: *** [Makefile:25: _build] Error 2
make[1]: Leaving directory '/home/jaime/gocode/src/github.com/elastic/opentelemetry-collector-components'
make: *** …
```
=> Exclude _build from ALL_MODULES

distributions/elastic-components/manifest.yaml, processor/elastictraceprocessor/processor_test.go, processor/lsmintervalprocessor/generated_component_test.go, processor/lsmintervalprocessor/processor_test.go
`factory#Create{Traces,Metrics}Processor` is now deprecated, update to use the non-deprecated methods.
=> Update to use factory#Create{Traces,Metrics}

connector/signaltometricsconnector/config/config.go, connector/signaltometricsconnector/connector.go, connector/signaltometricsconnector/connector_test.go, connector/signaltometricsconnector/factory.go, connector/signaltometricsconnector/go.mod, connector/signaltometricsconnector/internal/model/collectorinstanceinfo.go, connector/signaltometricsconnector/internal/model/collectorinstanceinfo_test.go, connector/signaltometricsconnector/internal/model/model.go, connector/signaltometricsconnector/testdata/logs/exponential_histograms/config.yaml, connector/signaltometricsconnector/testdata/logs/exponential_histograms/output.yaml, connector/signaltometricsconnector/testdata/logs/histograms/config.yaml, connector/signaltometricsconnector/testdata/logs/histograms/output.yaml, connector/signaltometricsconnector/testdata/logs/sum/config.yaml, connector/signaltometricsconnector/testdata/logs/sum/output.yaml, connector/signaltometricsconnector/testdata/metrics/exponential_histograms/output.yaml, connector/signaltometricsconnector/testdata/metrics/histograms/output.yaml, connector/signaltometricsconnector/testdata/metrics/sum/output.yaml, connector/signaltometricsconnector/testdata/traces/exponential_histograms/config.yaml, connector/signaltometricsconnector/testdata/traces/exponential_histograms/output.yaml, connector/signaltometricsconnector/testdata/traces/histograms/config.yaml, connector/signaltometricsconnector/testdata/traces/histograms/output.yaml, connector/signaltometricsconnector/testdata/traces/sum/config.yaml, connector/signaltometricsconnector/testdata/traces/sum/output.yaml
With `include_resource_attributes` white listining which
resource attributes to add as resource attributes to the
final metrics, single-writer is affected. Add the collectors
instance information restores single-writer.
Closes: https://github.com/elastic/opentelemetry-collector-components/issues/159
=> [connector/signaltometrics]Add otelcol instance info as res attribute

processor/elastictraceprocessor/generated_component_test.go
Update generated test with latest version of `mdatagen` to remove usage of deprecated methods.
=> [processor/elastictrace]Remove usage of deprecated NewTracesProcessor

distributions/elastic-components/manifest.yaml
Required to fix the open PRs to upgrade the components to v0.116.0
=> Bump up manifest component versions to v0.116.0

processor/lsmintervalprocessor/internal/data/expo/merge.go, processor/lsmintervalprocessor/processor.go
Detailed description on the changes available in godocs
=> [processor/lsminterval] Optimize pebble usage

processor/ratelimitprocessor/config.go, processor/ratelimitprocessor/config_test.go, processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/gubernator_test.go, processor/ratelimitprocessor/local.go, processor/ratelimitprocessor/local_test.go, processor/ratelimitprocessor/processor_test.go, processor/ratelimitprocessor/testdata/config.yaml
Configurable behavior on rate limit exceeded via config `throttle_behavior`.
- `error`: original behavior, return error immediately without forwarding event
- `delay`: delayed processing
=> [processor/ratelimit] Add `throttle_behavior` for optional delayed processing

processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/local.go, processor/ratelimitprocessor/local_test.go
Use select+timer rather than time.Sleep so
the delay is interrupted on context cancellation.
Also, speed up the local rate limiter delay
test from 1s to 100ms, to align with gubernator.
=> ratelimitprocessor: make delays interruptible

processor/lsmintervalprocessor/config/config.go, processor/lsmintervalprocessor/internal/merger/datapoints.go, processor/lsmintervalprocessor/internal/merger/limits/tracker.go, processor/lsmintervalprocessor/internal/merger/limits/tracker_test.go, processor/lsmintervalprocessor/internal/merger/merger.go, processor/lsmintervalprocessor/internal/merger/value.go, processor/lsmintervalprocessor/internal/merger/value_test.go, processor/lsmintervalprocessor/processor.go, processor/lsmintervalprocessor/processor_test.go, processor/lsmintervalprocessor/testdata/exphistogram_cumulative_overflow/input.yaml, processor/lsmintervalprocessor/testdata/exphistogram_cumulative_overflow/output.yaml, processor/lsmintervalprocessor/testdata/exphistogram_delta_overflow/input.yaml, processor/lsmintervalprocessor/testdata/exphistogram_delta_overflow/output.yaml, processor/lsmintervalprocessor/testdata/histogram_cumulative_overflow/input.yaml, processor/lsmintervalprocessor/testdata/histogram_cumulative_overflow/output.yaml, processor/lsmintervalprocessor/testdata/histogram_delta_overflow/input.yaml, processor/lsmintervalprocessor/testdata/histogram_delta_overflow/output.yaml, processor/lsmintervalprocessor/testdata/sum_cumulative_overflow/input.yaml, processor/lsmintervalprocessor/testdata/sum_cumulative_overflow/output.yaml, processor/lsmintervalprocessor/testdata/sum_delta_overflow/input.yaml, processor/lsmintervalprocessor/testdata/sum_delta_overflow/output.yaml
Introduces a metric overflow limit and removes the previous scope datapoint limit. Now, the limits follow the same hierarchy as the pmetric datastructure:
1. Resource limit
2. Scope limit
3. Metric limit
4. Datapoint limit
It is also possible to only set some of the limits, for example: if we only set datapoint limit then there will only be limit on the datapoint per metric and rest all will be without limit.
Closes: https://github.com/elastic/opentelemetry-collector-components/issues/141
=> [processor/lsminterval]Introduce metric overflow limit

processor/lsmintervalprocessor/config/config.go, processor/lsmintervalprocessor/go.mod, processor/lsmintervalprocessor/go.sum, processor/lsmintervalprocessor/internal/merger/key.go, processor/lsmintervalprocessor/internal/merger/key_test.go, processor/lsmintervalprocessor/processor.go, processor/lsmintervalprocessor/processor_test.go
This enables persisting client metadata from the incoming metrics, through aggregation, and into the produced metrics.
CPU overhead in the case where there's no metadata is within margin of error. Slight reduction in allocs because we're now using an AppendBinary method for marshalling keys.
```
goos: linux
goarch: amd64
pkg: github.com/elastic/opentelemetry-collector-components/processor/lsmintervalprocessor
cpu: AMD Ryzen 7 PRO 5850U with Radeon Graphics     
│ /tmp/old.txt │            /tmp/new.txt             │
│    sec/op    │    sec/op     vs base               │
Aggregation/sum_cumulative-16                    18.99µ ±  7%   18.24µ ± 14%        ~ (p=0.485 n=6)
Aggregation/sum_delta-16                         19.01µ ±  5%   19.05µ ±  9%        ~ (p=0.818 n=6) …
```
=> Add client metadata to key

receiver/loadgenreceiver/logs_bench_test.go, receiver/loadgenreceiver/metrics_bench_test.go, receiver/loadgenreceiver/traces_bench_test.go
Add benchmarks to facilitate upcoming loadgenreceiver performance improvements
Output
```
goos: linux
goarch: amd64
pkg: github.com/elastic/opentelemetry-collector-components/receiver/loadgenreceiver
cpu: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
BenchmarkLogsGenerator-16                   1453            820531 ns/op          541745 B/op       6447 allocs/op
BenchmarkMetricsGenerator-16                 663           1744985 ns/op         1418378 B/op      17053 allocs/op
BenchmarkTracesGenerator-16                  187           6486743 ns/op         7378511 B/op      29728 allocs/op
PASS
ok      github.com/elastic/opentelemetry-collector-components/receiver/loadgenreceiver  5.067s
```
=> [receiver/loadgen] Benchmark generators

loadgen/cmd/otelbench/README.md, loadgen/cmd/otelbench/flags.go, loadgen/cmd/otelbench/main.go
Make otelbench set the `concurrency` config in loadgenreceiver.
With `-concurrency=1,64`, output:
```
logs-otlp-1    	       3	6434488201 ns/op	         0 failed_logs/s	         0 failed_metric_points/s	         0 failed_requests/s	         0 failed_spans/s	       224.3 logs/s	         0 metric_points/s	        95.89 requests/s	         0 spans/s
metrics-otlp-1 	       8	1464059695 ns/op	         0 failed_logs/s	         0 failed_metric_points/s	         0 failed_requests/s	         0 failed_spans/s	         0 logs/s	      3177 metric_points/s	        56.01 requests/s	         0 spans/s
traces-otlp-1  	       1	13914055666 ns/op	         0 failed_logs/s	         0 failed_metric_points/s	         0 failed_requests/s	         0 failed_spans/s	         0 logs/s	         0 metric_points/s …
```
=> [otelbench] Add concurrency flag to simulate multiple agents

.github/workflows/checks.yml
Fix CI govulncheck.
```
=== Symbol Results ===
Vulnerability #1: GO-2025-3373
Usage of IPv6 zone IDs can bypass URI name constraints in crypto/x509
More info: https://pkg.go.dev/vuln/GO-2025-3373
Standard library
Found in: crypto/x509@go1.22.7
Fixed in: crypto/x509@go1.22.11
Example traces found:
Error:       #1: config/config.go:33:2: config.init calls zap.init, which eventually calls x509.CertPool.AppendCertsFromPEM
Error:       #2: config/config.go:273:37: config.validateMetricInfo[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottlspan.TransformContext] calls ottl.Parser[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/contexts/ottlspan.TransformContext].ParseConditions[github.com/open-telemetry/opentelemetry-collector-contrib/pkg/ottl/con …
```
=> Bump go version to 1.22.11 to pass govulncheck

processor/lsmintervalprocessor/processor.go, processor/lsmintervalprocessor/processor_test.go
The processor is no longer mutating, and will instead create a new pmetric.Metrics with just the metrics that will not be aggregated. This should be more efficient in the case where no or few metrics passed through.
This also allows us to remove some memory allocations from the benchmark code since it no longer needs to copy the input for each iteration.
=> lsmintervalprocessor: make processor non-mutating

.github/dependabot.yml, .github/workflows/checks.yml, internal/testutil/Makefile, internal/testutil/go.mod, internal/testutil/go.sum, internal/testutil/testutil.go, internal/testutil/testutil_test.go
Exposes and internal function to get a local endpoint: `GetAvailableLocalAddress`. Ipv4 code from https://github.com/open-telemetry/opentelemetry-collector/tree/main/internal/testutil
Used at:
- https://github.com/elastic/opentelemetry-collector-components/pull/324
- https://github.com/elastic/opentelemetry-collector-components/pull/39
=> test: add testutil internal package

connector/elasticapmconnector/go.mod, distributions/elastic-components/manifest.yaml, processor/ratelimitprocessor/go.mod
Depending on v0.0.0 is a problem for downstream components.
e.g.
```
$ go mod tidy -v
go: finding module for package github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector
go: found github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector in github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector v0.0.0-20250220025958-386ba0c4bced
go: downloading github.com/elastic/opentelemetry-collector-components/internal/sharedcomponent v0.0.0
go: <...> imports
github.com/elastic/opentelemetry-collector-components/connector/elasticapmconnector imports
github.com/elastic/opentelemetry-collector-components/internal/sharedcomponent: reading github.com/elastic/opentelemetry-collector-components/internal/sharedcomponent/go.m …
```
=> Fix sharedcomponent module version

processor/lsmintervalprocessor/processor.go
For low throughput cases when memtable flushes slowly the higher memtable size consumes (and hold to) more memory while not giving any benefits.
=> Reduce memtable size to 32MB

processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/gubernator_test.go, processor/ratelimitprocessor/ratelimiter.go
Closes https://github.com/elastic/hosted-otel-collector/issues/425.
Rate limit errors are now printed using the logger. The returned error is something more simple and generic indicating a failure from gubernator.
=> [processor/ratelimitprocessor] Do not leak ratelimiter errors to the client

loadgen/cmd/otelbench/.chloggen/add-println-otelbench.yaml, loadgen/cmd/otelbench/main.go
Closes https://github.com/elastic/opentelemetry-collector-components/issues/391.
If we ran otelbench directly (example `go build -o otelbench . && ./otelbench --config=my-config.yaml`), there are no printing lines in case of error since there is only a log in the benchmark context. This PR fixes that.
Example output in case of error:
```
$ go build -o otelbench . && ./otelbench --config=my-config.yaml 
failed to create SDK: binding address localhost:8888 for Prometheus exporter: listen tcp 127.0.0.1:8888: bind: address already in use
logs-otlp-1                    0                       NaN ns/op
failed to create SDK: binding address localhost:8888 for Prometheus exporter: listen tcp 127.0.0.1:8888: bind: address already in use
logs-otlphttp-1                0                       NaN …
```
=> [loadgen/otelbench] Add println on error

.github/workflows/bump_otelbench.yaml
One of the script files failed with lack of permissions. To ensure this does not happen, let's make sure that we add execute permissions before executing any script file.
Example failure: https://github.com/elastic/opentelemetry-collector-components/actions/runs/13700451370/job/38312682930
=> [workflow/otelbench] Add execute permissions to script files

.github/workflows/bump_otelbench.yaml
Fix for unsafe usage of input variable inside run step.
=> Update unsafe usage of variable in run command

.github/workflows/release_otelbench.yaml
The workflow_dispatch trigger was added so we could trigger the release after the CHANGELOG was updated. We now need to remove this, because otherwise we can start releasing the `otelbench` image with different changes for the same version.
This way, the workflow to release is:
- Have at least one change in otelbench (this forces a new changelog fragment).
- Bump a new release - this will update the CHANGELOG, only if there are any new changes.
- The previous step will create a PR that once merged triggers the workflow to release a new image.
=> [workflow/release_otelbench] Remove workflow_dispatch trigger

distributions/elastic-components/manifest.yaml
This PR introduces support for `bearertokenauth` as an authentication extension, allowing the `elasticapmreceiver` to authenticate clients using secret tokens.
- Build an OTel collector using the manifest in this PR
- Add the following to your OTel collector configuration
```
receivers:
otlp/withauth:
protocols:
grpc:
endpoint: $MY_ENDPOINT
auth:
authenticator: bearertokenauth/withscheme
http:
endpoint: $MY_ENDPOINT
auth:
authenticator: bearertokenauth/withscheme
extensions:
bearertokenauth/withscheme:
scheme: "Bearer"
token: "my_token"
```
- Use [`sendotlp`](https://github.com/elastic/otel-apm-e2e-poc/tree/main/sendotlp) to send test data
```
OTEL_RESOURCE_ATTRIBUTES="service.name=sendotlp,some.resource.attribute=resource.attr" go run ./ -endpoint="MY_ENDPOINT" -secret-token="my_token" …
```
=> Add support for bearertokenauth

receiver/elasticapmreceiver/internal/mappers/intakeV2ToDerivedFields.go
With the latest release of `opentelemetry-lib` we can now reuse elastic specific attributes defined as constants in the `elasticattr` package.
This PR replaces in-place strings with the constants defined in `opentelemetry-lib`.
=> [IntakeV2 receiver] Use elasticattr constants from opentelemetry-lib

connector/elasticapmconnector/connector.go
When constructing the internal lsminterval processor and signaltometrics connector, use the correct component type in the processor/connector settings. This is necessary for us to update to newer versions of opentelemetry-collector core, which is strict about the component type.
=> connector/elasticapmconnector: fix component types

.github/dependabot.yml
Groups dependabot depenecies by ownership to allow easier reviews and a smaller number of PRs while keeping the dependencies within teams.
=> Group dependabot dependencies by ownership

receiver/loadgenreceiver/config.go, receiver/loadgenreceiver/factory.go, receiver/loadgenreceiver/metrics.go, receiver/loadgenreceiver/metrics_test.go
AddCounterAttr, if true, adds a loadgenreceiver_counter resource attribute containing increasing counter value to the generated metrics.
It can be used to workaround timestamp precision and duplication detection of backends,
e.g. Elasticsearch TSDB version_conflict_engine_exception with millisecond-precision timestamp mapping,
which will be triggered when loadgenreceiver generates metrics too quickly such that
there exists data points of the same metric with the same dimensions within a millisecond but different nanoseconds.
Defaults to true.
Alternative to #493 but with little to no perf overhead.
=> Add config `metrics::add_counter_attr` (default=true) to workaround TSDB version conflict by adding loadgenreceiver_counter resource attribute

connector/elasticapmconnector/config.go, connector/elasticapmconnector/config_test.go, connector/elasticapmconnector/testdata/config/full.yaml
This PR is exposing lsm intervals configuration to `elasticapmconnector` which makes it possible to configure custom aggregation intervals. This is useful in integration testing where the default intervals are not practical to use. If custom intervals were not provided the config will default to the old intervals values.
=> elasticapmconnector: allow setting custom lsm intervals

go.mod
This file is not used and was accidentally added in https://github.com/elastic/opentelemetry-collector-components/pull/294.
=> Delete go.mod in root

.github/workflows/bump_otelbench.yaml, .github/workflows/changelog_otelbench.yaml
root go.mod is deleted. Use tools go.mod.
=> Fix changelog otelbench workflow gomod path

processor/ratelimitprocessor/documentation.md, processor/ratelimitprocessor/factory.go, processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/gubernator_test.go, processor/ratelimitprocessor/internal/telemetry/attributes.go, processor/ratelimitprocessor/local.go, processor/ratelimitprocessor/local_test.go, processor/ratelimitprocessor/metadata.yaml, processor/ratelimitprocessor/processor.go, processor/ratelimitprocessor/processor_test.go, processor/ratelimitprocessor/ratelimiter.go
This PR:
- Removes the too many requests error wrongly introduced in https://github.com/elastic/opentelemetry-collector-components/pull/562.
- Removes the duplicate code to declare metrics
=> [ratelimiter] Remove wrong error, remove duplicate code

processor/ratelimitprocessor/documentation.md, processor/ratelimitprocessor/factory.go, processor/ratelimitprocessor/internal/metadata/generated_telemetry.go, processor/ratelimitprocessor/internal/metadatatest/generated_telemetrytest.go, processor/ratelimitprocessor/internal/metadatatest/generated_telemetrytest_test.go, processor/ratelimitprocessor/metadata.yaml, processor/ratelimitprocessor/processor.go, processor/ratelimitprocessor/processor_test.go
This PR is to add two more telemetry metrics for rate limit processor:
- `otelcol_ratelimit.concurrent_requests`: records the number of requests that are being processed by the rate limiter at any given moment. 
- `otelcol_ratelimit.request_duration`: Measures the duration of time taken to process each rate limiting request.
```
{
"_index": ".ds-metrics-apm.app.hosted_otel_collector-default-2025.05.29-000001",
"_id": "nfKmH5cBiYL18_Vh6pN_",
"_version": 1,
"_source": {
"@timestamp": "2025-05-30T05:25:21.304Z",
"agent": {
"name": "otlp",
"version": "unknown"
},
"data_stream": {
"dataset": "apm.app.hosted_otel_collector",
"namespace": "default",
"type": "metrics"
},
"event": {
"ingested": "2025-05-30T05:25:22.000Z"
},
"labels": {
"orchestrator_cluster_name": "default", …
```
=> [ratelimit] Add concurrent_requests and request_duration telemetry metrics

processor/ratelimitprocessor/factory.go, processor/ratelimitprocessor/metadata.yaml, processor/ratelimitprocessor/processor.go, processor/ratelimitprocessor/processor_test.go
With this fix, we can see metadata keys in documents, for example:
```
{
"_index": ".ds-metrics-apm.app.hosted_otel_collector-default-2025.05.31-000001",
"_id": "S51jMpcBnkooZBdL-MnS",
"_version": 1,
"_source": {
"@timestamp": "2025-06-02T20:45:01.030Z",
"agent": {
"name": "otlp",
"version": "unknown"
},
"data_stream": {
"dataset": "apm.app.hosted_otel_collector",
"namespace": "default",
"type": "metrics"
},
"event": {
"ingested": "2025-06-02T20:45:02.000Z"
},
"labels": {
"orchestrator_cluster_name": "default",
"orchestrator_deploymentslice": "",
"orchestrator_environment": "default",
"x-elastic-project-id": "local"
},
"metricset": {
"name": "app"
},
"otelcol_ratelimit": {
"concurrent_requests": 8
}
}
}
```
=> Add metadata keys for rate limiter telemetry metrics

extension/apmconfigextension/README.md, extension/apmconfigextension/elastic/centralconfig/fetcher.go, extension/apmconfigextension/elastic/centralconfig/fetcher_test.go, extension/apmconfigextension/integration_test.go, extension/apmconfigextension/opamp_callbacks_test.go
"text/json" is a legacy/deprecated mime type for JSON content. (Reference: https://en.wikipedia.org/wiki/JSON#Metadata_and_schema)
The in-dev central config work for EDOT Node.js is checking the contentType of remote config before parsing it. I noticed that "text/json" was being used.  FWIW to EDOT Java central-config code does not check the content type so changing it will not break the Java OTel distro at least.
=> [extension/apmconfig]: use "application/json" content type for remote config, rather than deprecated "text/json"

Makefile, README.md, distributions/elastic-components/manifest.yaml
I noticed EDOT collector doesn't have `cumulativetodelta` processor. It seems useful to include it because currently APM only supports delta metrics FWIU. For example, if scraping prometheus endpoints with the collector, this processor can be used to get them into APM.
I also fixed cross compile on MacOS - `builder` was also being built with the provided `GOOS` causing it to be not executable.
/cc @codefromthecrypt
=> Add cumulativetodelta processor

extension/apmconfigextension/elastic/centralconfig/fetcher.go, extension/apmconfigextension/elastic/centralconfig/fetcher_test.go, extension/apmconfigextension/integration_test.go
Fixes https://github.com/elastic/opentelemetry-collector-components/issues/606
=> fix: return empty remote configurations

.github/workflows/checks.yml
https://pkg.go.dev/vuln/GO-2025-3750 was announced earlier today
https://groups.google.com/g/golang-announce/c/ufZ8WpEsA3A fix is in go 1.24.4 and 1.23.10
=> Bump golang version in CI to fix govulncheck

extension/apmconfigextension/go.mod, extension/apmconfigextension/go.sum
Remove internal package Go replacement.
We could consider releasing the internal package if it's used more broadly.
=> chore: pin testutil package commit version

connector/elasticapmconnector/config.go, connector/elasticapmconnector/testdata/logs/service_summary/aggregated_metrics.yaml, connector/elasticapmconnector/testdata/metrics/service_summary/aggregated_metrics.yaml, connector/elasticapmconnector/testdata/traces/transaction_metrics/aggregated_metrics.yaml
With the fixes for exponential histogram, it should perform on-par with histograms ([slack thread](https://elastic.slack.com/archives/C0680QCJKMM/p1743179432353619)).
Closes: https://github.com/elastic/opentelemetry-collector-components/issues/370
=> [connector/elasticapm]Use exponential histogram from txn metrics

processor/lsmintervalprocessor/processor.go, processor/lsmintervalprocessor/processor_test.go
A followup PR to https://github.com/elastic/opentelemetry-collector-components/pull/621 that adds forgotten unit tests to verify that the internal metrics are reported as they should. It additionally fixes `shutdown` call for the internal metrics telemetry builder.
=> lsmintervalprocessor: fix telemetry builder shutdown and add internal telemetry tests

loadgen/cmd/otelbench/.chloggen/main.yaml, loadgen/cmd/otelbench/main.go
+ Part of https://github.com/elastic/hosted-otel-collector/issues/921
+ Uses the existing `--test.count` flag available via the testing.Benchmarks runner to run benchmark for n iterations to get more stable results.
=> loadgen: add support for running benchmark for n iterations

extension/apikeyauthextension/authenticator.go, extension/apikeyauthextension/authenticator_test.go, extension/apikeyauthextension/go.mod
Updates the extension to return a `status.Error` type (which wraps the `status.Status` type) instead of a plain `error` type. This allows propagating the status code and message from the extension to the collector.
This is similar to what the upstream OTLP receiver does:
https://github.com/open-telemetry/opentelemetry-collector/blob/v0.129.0/receiver/otlpreceiver/otlphttp.go#L183-L192
=> apikeyauthextension: propagate status code in errs

processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/gubernator_test.go, processor/ratelimitprocessor/local.go, processor/ratelimitprocessor/local_test.go, processor/ratelimitprocessor/processor.go, processor/ratelimitprocessor/processor_test.go
Wraps the error returned by the rate limiter with the grpc code library to ensure that the code is propagated to the client. For non 5xx errors, the code is set to `codes.ResourceExhausted`, which is the appropriate code for rate limiting errors.
Part of elastic/hosted-otel-collector#991
=> ratelimitprocessor: Wrap error with code for 429

connector/elasticapmconnector/go.mod
It seems when building with ocb (tried with v0.129.0), the [replace directive](https://github.com/elastic/opentelemetry-collector-components/blob/00f56bcca5c08e6317dc8f61ff44bfdb52862213/connector/elasticapmconnector/go.mod#L120) is ignored. Bumping up the version so the correct version is picked even in this case.
=> Bump up lsminterval version for elastic apm connector

connector/profilingmetricsconnector/config.go, connector/profilingmetricsconnector/connector.go, connector/profilingmetricsconnector/connector_test.go, connector/profilingmetricsconnector/general_aggregation.go, connector/profilingmetricsconnector/general_aggregation_test.go
Allow more detailed aggregation and classification of metrics from profiling information.
Treemap visualization of the top 25 entries generated by classification:
=> profilingmetricsconnector: add (costum)? classification

loadgen/cmd/otelbench/.chloggen/f_add-shuffle-flag.yaml, loadgen/cmd/otelbench/Makefile, loadgen/cmd/otelbench/flags.go, loadgen/cmd/otelbench/main.go
Adds a new `-shuffle` flag to randomize the order of signals in the benchmark runs. This is useful for cases where multiple instances of the loadgen are run concurrently, allowing more varied benchmarking.
=> loadgen: Allow shuffling signal benchmark order

loadgen/cmd/otelbench/.chloggen/setdatapath_signals.yaml, loadgen/cmd/otelbench/README.md, loadgen/cmd/otelbench/config.yaml, loadgen/cmd/otelbench/flags.go, loadgen/cmd/otelbench/main.go
This adds the ability to provide `<signal>-data-path` parameter to your tests in order to provide custom input for your tests
The PR includes also the update of the name of the test in case the data-path is provided
```bash
./loadgen -config="./config_traces.yaml" -concurrency=60 -test.benchtime=1m -test.count=3 -traces-data-path="./testdata/tracesTestFile.jsonl"
BenchmarkOTelbench/traces-otlp-tracesTestFile-60    	    7710	   9093050 ns/op	         0 failed_logs/s	         0 failed_metric_points/s	         0 failed_requests/s	         0 failed_spans/s	         0 logs/s	         0 metric_points/s	       110.0 requests/s	       549.9 spans/s
```
The above is handy when you want to provide custom load for the benchmark test we want to run
Verified that the the custom data path is applied in …
=> [Otelbench] Set datapath for signals

.github/CODEOWNERS
Integrations are an essential part for the @elastic/elastic-agent-data-plane team.
Follow up to https://github.com/elastic/opentelemetry-collector-components/pull/96
=> CODEOWNERS: Assign @elastic/elastic-agent-data-plane and @elastic/ecosystem

receiver/elasticapmintakereceiver/receiver.go, receiver/elasticapmintakereceiver/receiver_test.go
The `elasticapmintakereceiver` needs to respect `include_metadata` server config and propagate client request metadata to the handler when it's set.
=> [elasticapmintakereceiver] Propagate request metdata when include_metadata is set

extension/apikeyauthextension/authenticator.go, extension/apikeyauthextension/authenticator_test.go, extension/apikeyauthextension/go.mod, processor/ratelimitprocessor/go.mod, processor/ratelimitprocessor/gubernator.go, processor/ratelimitprocessor/local.go, processor/ratelimitprocessor/processor_test.go, processor/ratelimitprocessor/ratelimiter.go
+ Improve the gRPC error info with additional details which can be leveraged in the upstream wrapper component to provide detailed error info to users.
=> improve errorinfo for ratelimiter and auth errors

receiver/elasticapmintakereceiver/internal/mappers/intakeV2ToOtlpTopLevelFields.go, receiver/elasticapmintakereceiver/testdata/invalid_ids_expected.yaml, receiver/elasticapmintakereceiver/testdata/metricsets_expected.yaml, receiver/elasticapmintakereceiver/testdata/spans_expected.yaml, receiver/elasticapmintakereceiver/testdata/transactions_spans_expected.yaml, receiver/elasticapmintakereceiver/testdata/unknown-span-type_expected.yaml
This likely happened when we added error/LogRecord support.
The waterfall chart did not work - spans were not shown, only the root transaction. And then looking at the documents, each span in a given trace fog a given transaction had the same `span.id` on all the spans and on the transaction. So basically `span.id`s were incorrect.
In the elastic apm data model, on each span we have a `transaction.id` field, which is the id of the root transaction in the given trace. However, this isn't needed anymore.
At the same time, an error and a transaction also has a `transaction.id` (errors may or may not have it)
So if the given event is an error or a transaction, and we turn those into pdata, then we need to use this `transaction.id` as the span id. But if the given event is a span, we can just …
=> [elasticapmintakereceiver] Fix: do not set transaction.id on spans as span.id

connector/profilingmetricsconnector/config.go, connector/profilingmetricsconnector/connector.go, connector/profilingmetricsconnector/frame.go
This PR adds fixed frame-type metrics (self-cpu, exclusive) that are extracted by classifying each incoming `Sample` into one or more categories. 
The metrics remain comparable even when aggregated over varying time windows on the backend: they can be expressed as a ratio of `metricCount / totalSampleCount`.
**TODO:** 
- ~Compile, run, test~
=> profilingmetricsconnector: Add frame type metrics (self-cpu)
